### ISSUE TITLE
I could not add()

### ISSUE THREAD

**Issue by parkerwu** [christian-putzke/CardDAV-PHP#10]
Get card per id : OK
get() :  OK 

add() -> server said not found ?

**Comment by christian-putzke** [comment]
The add method does two requests. At first it generates a random vcard-id and then it tries do GET a vcard with this generated vcard-id from the server. If this result returns a "not found" the vcard-id is not in use and can be used for the PUT request to put the vcard with the generated vcard-id on the server.
