### ISSUE TITLE
curl_setopt() issue

### ISSUE THREAD

**Issue by xbgmsharp** [christian-putzke/CardDAV-PHP#14]
On version v0.5.2
carddav.php:503 curl_setopt() expects exactly 3 parameters, 2 given (2)
I believe the same apply to version  0.6.

The error appear on Debian Squezze with php5
$ php -v
PHP 5.3.3-7+squeeze13

**Comment by xbgmsharp** [comment]
This in my repo
https://github.com/xbgmsharp/sogosync/commit/36395f7125451b9e685aedeabf1a09ccbd786766

**Comment by christian-putzke** [comment]
This bug does not exists in the latest version.
