### ISSUE TITLE
osx server snow leopard - auth bug -> fixed

### ISSUE THREAD

**Issue by wingsuitist** [christian-putzke/CardDAV-PHP#2]
I couldn't authenticate to the OSX Server Snow Leopard and to fix it I changed the auth method:

```
        //curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
        curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
```

Of course CURLAUTH_ANY should also support DIGEST, but it seams that the server denies the login if you use it! With DIGEST it works perfectly.

**Comment by christian-putzke** [comment]
Thanks for the report. Maybe you can provide me a test account on your osx server, then I can try to fix the issue without harming other authentication methods.

**Comment by christian-putzke** [comment]
I can't reproduce that error. Maybe it's just on a specifiy version.
