### ISSUE TITLE
don't work with darwin calendarserver 

### ISSUE THREAD

**Issue by lexusburn** [christian-putzke/CardDAV-PHP#5]
Hello,

i had installed darwin calendarserver (open source caldav/carddav implementation).
it's working fine with osx adressbook and ios. 
and it works with atmail webmail interface too.

if i want to use it with your carddav-plugin for roundcubemail i get the following problems:

on setup i have to enter hostname with port because without it i get the follwing error: "Serverfehler! (Internal Server Error)".
after this it creates the new carddav-record anyway and i can use it.

if i setup hostname with port (8800) i get no error on setup.

if i want to sync my contacts with carddav server i get always (on both setups) the following message in frontend: "Serverfehler! (Internal Server Error)" and in logfile this: "CardDAV-Server XML-Response is malformed. Synchronization aborted!"

if you need an account to test against my carddav-server i can create one for you.

best regards,
Frederic

**Comment by lexusburn** [comment]
I have tested a little bit more.

if i enter the full path as "server", i get the contacts.
now i have given the full path like this: [hostname]:8800/addressbooks/**uids**/[username]/addressbook/ to get it working.

With this setup can i get most data from my contacts

**Comment by christian-putzke** [comment]
Hi!
It's correct that you have to use the complete url for the usage of my CardDAV Client. Maybe I can add a functionality that trys to figure out the complete CardDAV addressbook url from the simple url. But I'm not sure if that is that easy. But I'll keep that in mind.

**Comment by lexusburn** [comment]
Hi,

it would be nice if you can add some information to the readme-file for other new roundcube-users.

if you want to add an functionality to figure out correct url, i think it is simple with darwin calendarserver.
don't now if it is simple like this with other servers.

if i only connect to my hostname with username/password on port 8800 it get the needed informations.
if you want to have an look on these, i can create a sample accout for you.

**Comment by christian-putzke** [comment]
Hi,
a list of CardDAV Servers and wich URL they need to work with my Roundcube CardDAV Plugin is already planned. Have a look at the roadmap: https://github.com/graviox/Roundcube-CardDAV/wiki/Roadmap

If you still have any problems with your CardDAV server you can send me a sample account and I'll have a look.

**Comment by lexusburn** [comment]
Hello,

Am 13.03.2012 um 21:35 schrieb Christian Putzke:

> Hi,
> a list of CardDAV Servers and wich URL they need to work with my Roundcube CardDAV Plugin is already planned. Have a look at the roadmap: https://github.com/graviox/Roundcube-CardDAV/wiki/Roadmap

Sounds good! :-)

> If you still have any problems with your CardDAV server you can send me a sample account and I'll have a look.

Had no other problems found at the moment, except the problems that are roundcube-related as you said.
But i had created an account for you if you want to test against darwin calendarserver.

You can logon with the account credentials that i send to you via email with a browser and have a look on the data structure if you want.

best regards
lexusburn
