### ISSUE TITLE
Does not import email addresses of type 'andere'

### ISSUE THREAD

**Issue by holgerdor** [christian-putzke/CardDAV-PHP#7]
Hello,

I am using CardDAV-PHP with owncloud 3.0 which keeps the contacts of my MacBook. Unfortunately the email adresses of type 'Andere' are not imported in roundcube. The types 'Privat' and 'Arbeit' work fine.

**Comment by christian-putzke** [comment]
I'll have a look at it but my first impression is that this is a bug from Roundcube because I just transfer the vCard from the CardDAV Server as it is. But I'll check it.

**Comment by holgerdor** [comment]
Thank you for checking.

**Comment by christian-putzke** [comment]
Do you use Roundcube 3.0 stable or the version from git? In Roundcube 3.0 stable I can't define and E-Mail type.

**Comment by holgerdor** [comment]
I am using Roundcube 0.7.x stable I think. Where can I find the version of roundcube once it is installed?

In roundcube when creating a new contact, I can choose a type, see http://windwolke.dyndns.org/roundcube.png.

But I did not create the contact in roundcube directly but on my MacBook which is synced with owncloud 3.0.

**Comment by holgerdor** [comment]
I did some further test with this sample vcard: http://windwolke.dyndns.org/John%20Doe.vcf

It is possible to import this in roundcube and I can see both email addresses.
My MacBook syncs with owncloud 3.0.0 and can see both email addresses in owncloud.
When I sync owncloud with roundcube, one of John Doe's email addresses disappears.

**Comment by christian-putzke** [comment]
I'm sorry! I missunderstand your issue. I thought you added the contacts in the owncloud webinterface and the email does not appear in roundcube. I'll have a look at your issue again.

**Comment by christian-putzke** [comment]
Can you please have a look at the vCard in the Roundcube database at the table carddav_contacts. Is the vCard the same as in your owncloud database?

**Comment by holgerdor** [comment]
Yes, the vcard in owncloud database and carddav_contacts is the same.

**Comment by christian-putzke** [comment]
Hmm, then it seems to be a bug in Roundcube itselfs because I just use the Roundcube internal addressbook classes but I'll have a closer look soon.

**Comment by christian-putzke** [comment]
This bug is not releated to this CardDAV PHP connector. It's a bug from roundcube if its no fixed already ;)
