### ISSUE TITLE
XML Parser Warning

### ISSUE THREAD

**Issue by xelax90** [christian-putzke/CardDAV-PHP#8]
Hello,

your tool just made my day ;-)
but I've found a small bug: The XML Parser throws the following warnings when using PHP 5.2.14 with libxml 2.6.32 and SabreDAV:

Warning: SimpleXMLElement::__construct() [simplexmlelement.--construct]: Entity: line 2: parser warning : xmlns:d: 'DAV:' is not a valid URI in carddav.php on line 354

Warning: SimpleXMLElement::__construct() [simplexmlelement.--construct]: <multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:iet in carddav.php on line 354

Warning: SimpleXMLElement::__construct() [simplexmlelement.--construct]: ^ in carddav.php on line 354

They do not appear when using PHP 5.3.1 and libxml 2.7.3. I fixed this issue by adding this line to your clean_response function:

$response = preg_replace('/xmlns:d=\"[^\"]*\"/i', '', $response);

**Comment by christian-putzke** [comment]
Thanks for you comment. I'll have a look at it.

**Comment by christian-putzke** [comment]
I'll close that issue because it appear just on "older" PHP versions. PHP 5.3 will be a requirement with the next update. But thanks for your feedback!
