### ISSUE TITLE
Would like to use this for Caller ID matching

### ISSUE THREAD

**Issue by lgaetz** [christian-putzke/CardDAV-PHP#9]
Project: Caller ID Superfecta  https://github.com/tm1000/Caller-ID-Superfecta/

I would like to adapt this code to look up a name for a known phone number from an OS x server.  I am not very strong with PHP and I am hoping to get a bit of help on how to structure the query.  I assume I can adapt the simple query for this purpose:

```
$carddav = new carddav_backend('https://davical.example.com/user/contacts/');
$carddav->set_auth('username', 'password');
echo $carddav->get();
```

I have confirmed that I have a server connection with the supplied "check connection" code, but I don't know how to actually search records for the phone number.  Any pointers?

**Comment by christian-putzke** [comment]
The CardDAV PHP client does not have the functionality to search directly on the CardDAV server for specific vCard parameters because this feature is still under development on many CardDAV servers and does not work very well.
So you have to get() all vCards from your server and search manually for the phone number. There are a lot of PHP vCard classes with should provide search methods for vCards.

**Comment by lgaetz** [comment]
Thanks for the reply back.  So my preliminary testing with these lines:

```
echo var_dump($carddav->check_connection());
echo var_dump($carddav->get());
```

gives this output:

```
bool(true)
bool(false)
```

I think this is telling me that I am getting a connection but that the get query is failing.  Is there something obvious here that I am missing?

**Comment by christian-putzke** [comment]
You can try to use this:
var_dump($carddav->get(false, true));

This will return the raw and unmodified xml from the CardDAV Server if it's got a http code of 200 or 207. If you get also a bool (false) then you can have a look at your CardDAV server log and see which http code is included in the CardDAV server response.

**Comment by christian-putzke** [comment]
I've released an update of CardDAV PHP. Now you have the possibility to debug your issue.
Try this:
$carddav->enable_debug();
$carddav->get();
var_dump($carddav->get_debug());

**Comment by lgaetz** [comment]
Thanks for your help.  With your new debug code, I am able to narrow the problem down to the server:

"The PROPFIND method is not allowed for the requested URL."

You can close this issue.  I appreciate your help.

**Comment by lgaetz** [comment]
What is the proper way to pass a port with the URL?  I have just been informed that I need to use a specific port for queries on the carddav server.

**Comment by christian-putzke** [comment]
Just type it behind the URL. Here is an example:
https://example.com:8443/dav/test/
